//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.05 at 10:42:35 AM COT 
//


package entities;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@Entity
@Table(name = "Campeonato")
public class Campeonato {

    @Id
    @Basic(optional = false)
    @NotNull
    @Column
    protected String nombre;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoE")
    protected List<Escuderia> escuderias;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoM")
    protected List<Monoplaza> monoplazas;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoP")
    protected List<Piloto> pilotos;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoA")
    protected List<Apuesta> apuestas;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoPa")
    protected List<Pais> paises;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoU")
    protected List<Usuario> usuarios;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoPr")
    protected List<Premio> calendario;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "campeonatoCir")
    protected List<Circuito> circuitos;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the escuderias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the escuderias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEscuderias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Escuderia }
     * 
     * 
     */
    public List<Escuderia> getEscuderias() {
        if (escuderias == null) {
            escuderias = new ArrayList<Escuderia>();
        }
        return this.escuderias;
    }

    /**
     * Gets the value of the monoplazas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monoplazas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonoplazas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Monoplaza }
     * 
     * 
     */
    public List<Monoplaza> getMonoplazas() {
        if (monoplazas == null) {
            monoplazas = new ArrayList<Monoplaza>();
        }
        return this.monoplazas;
    }

    /**
     * Gets the value of the pilotos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pilotos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPilotos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Piloto }
     * 
     * 
     */
    public List<Piloto> getPilotos() {
        if (pilotos == null) {
            pilotos = new ArrayList<Piloto>();
        }
        return this.pilotos;
    }

    /**
     * Gets the value of the apuestas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apuestas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApuestas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Apuesta }
     * 
     * 
     */
    public List<Apuesta> getApuestas() {
        if (apuestas == null) {
            apuestas = new ArrayList<Apuesta>();
        }
        return this.apuestas;
    }

    /**
     * Gets the value of the paises property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paises property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaises().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pais }
     * 
     * 
     */
    public List<Pais> getPaises() {
        if (paises == null) {
            paises = new ArrayList<Pais>();
        }
        return this.paises;
    }

    /**
     * Gets the value of the usuarios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usuarios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsuarios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Usuario }
     * 
     * 
     */
    public List<Usuario> getUsuarios() {
        if (usuarios == null) {
            usuarios = new ArrayList<Usuario>();
        }
        return this.usuarios;
    }

    /**
     * Gets the value of the calendario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calendario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalendario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Premio }
     * 
     * 
     */
    public List<Premio> getCalendario() {
        if (calendario == null) {
            calendario = new ArrayList<Premio>();
        }
        return this.calendario;
    }

    /**
     * Gets the value of the circuitos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the circuitos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCircuitos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Circuito }
     * 
     * 
     */
    public List<Circuito> getCircuitos() {
        if (circuitos == null) {
            circuitos = new ArrayList<Circuito>();
        }
        return this.circuitos;
    }
    
    

}
