//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.05 at 10:42:35 AM COT 
//


package entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@Entity
@Table(name = "Premio")
public class Premio {

    @Id
    @Basic(optional = false)
    @NotNull
    @Column
    private Integer idPremio;
    
    @JoinColumn(name = "campeonatoPr", referencedColumnName = "campeonatoPr")
    @ManyToOne
    private Campeonato campeonato;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "sCarrera")
    private List<SesionCarrera> sesionesCarrera;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "sClasifi")
    private List<SesionClasificacion> sesionesClasificacion;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "sPractica")
    private List<SesionPractica> sesionesPractica;

    @OneToOne
    private Circuito circuito;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "premioC")
    private List<Calificacion> calificaciones;

    @Size(max = 30)
    @Column
    private String nombre;

    @Column
    private Date fechaInicio;

    @Column
    private Date fechaFin;

    /**
     * Gets the value of the sesionesCarrera property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sesionesCarrera property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSesionesCarrera().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SesionCarrera }
     * 
     * 
     */
    public List<SesionCarrera> getSesionesCarrera() {
        if (sesionesCarrera == null) {
            sesionesCarrera = new ArrayList<SesionCarrera>();
        }
        return this.sesionesCarrera;
    }

    /**
     * Gets the value of the sesionesClasificacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sesionesClasificacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSesionesClasificacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SesionClasificacion }
     * 
     * 
     */
    public List<SesionClasificacion> getSesionesClasificacion() {
        if (sesionesClasificacion == null) {
            sesionesClasificacion = new ArrayList<SesionClasificacion>();
        }
        return this.sesionesClasificacion;
    }

    /**
     * Gets the value of the sesionesPractica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sesionesPractica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSesionesPractica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SesionPractica }
     * 
     * 
     */
    public List<SesionPractica> getSesionesPractica() {
        if (sesionesPractica == null) {
            sesionesPractica = new ArrayList<SesionPractica>();
        }
        return this.sesionesPractica;
    }

    /**
     * Gets the value of the circuito property.
     * 
     * @return
     *     possible object is
     *     {@link Circuito }
     *     
     */
    public Circuito getCircuito() {
        return circuito;
    }

    /**
     * Sets the value of the circuito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Circuito }
     *     
     */
    public void setCircuito(Circuito value) {
        this.circuito = value;
    }

    /**
     * Gets the value of the calificaciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calificaciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalificaciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Calificacion }
     * 
     * 
     */
    public List<Calificacion> getCalificaciones() {
        if (calificaciones == null) {
            calificaciones = new ArrayList<Calificacion>();
        }
        return this.calificaciones;
    }

    /**
     * Gets the value of the idPremio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdPremio() {
        return idPremio;
    }

    /**
     * Sets the value of the idPremio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdPremio(Integer value) {
        this.idPremio = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the fechaInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * Sets the value of the fechaInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicio(Date value) {
        this.fechaInicio = value;
    }

    /**
     * Gets the value of the fechaFin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * Sets the value of the fechaFin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaFin(Date value) {
        this.fechaFin = value;
    }

    public Campeonato getCampeonato() {
        return campeonato;
    }

    public void setCampeonato(Campeonato campeonato) {
        this.campeonato = campeonato;
    }

    
    
}
