//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.05 at 10:42:35 AM COT 
//


package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;

@Entity
@Table(name = "ResultadoClasificacion")
public class ResultadoClasificacion implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="resultadoclasificacion_id", nullable = false, unique = true)
    private Integer idResultado;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sesionclasificacion_id")
    private SesionClasificacion sesionClasificacion;
    
    @JoinColumn(name="piloto_id")
    private Piloto piloto;

    @Column
    private Double q1;

    @Column
    private Double q2;

    @Column
    private Double q3;

    @Column
    private Integer vueltas;

    @Column
    private Integer posicion;

    @Column
    private Double recordVuelta;

        @XmlIDREF
    public SesionClasificacion getSesionClasificacion() {
        return sesionClasificacion;
    }

    public void setSesionClasificacion(SesionClasificacion sesionClasificacion) {
        this.sesionClasificacion = sesionClasificacion;
    }



    
    /**
     * Gets the value of the piloto property.
     * 
     * @return
     *     possible object is
     *     {@link Piloto }
     *     
     */
        @XmlIDREF
    public Piloto getPiloto() {
        return piloto;
    }

    /**
     * Sets the value of the piloto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Piloto }
     *     
     */
    public void setPiloto(Piloto value) {
        this.piloto = value;
    }

    /**
     * Gets the value of the sesionClasificacion property.
     * 
     * @return
     *     possible object is
     *     {@link SesionClasificacion }
     *     
     */


    /**
     * Gets the value of the idResultado property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @XmlID
    public String getIdXml() {
        return idResultado+"";
    }
    public Integer getIdResultado() {
        return idResultado;
    }

    /**
     * Sets the value of the idResultado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdResultado(Integer value) {
        this.idResultado = value;
    }

    /**
     * Gets the value of the q1 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ1() {
        return q1;
    }

    /**
     * Sets the value of the q1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ1(Double value) {
        this.q1 = value;
    }

    /**
     * Gets the value of the q2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ2() {
        return q2;
    }

    /**
     * Sets the value of the q2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ2(Double value) {
        this.q2 = value;
    }

    /**
     * Gets the value of the q3 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ3() {
        return q3;
    }

    /**
     * Sets the value of the q3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ3(Double value) {
        this.q3 = value;
    }

    /**
     * Gets the value of the vueltas property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVueltas() {
        return vueltas;
    }

    /**
     * Sets the value of the vueltas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVueltas(Integer value) {
        this.vueltas = value;
    }

    /**
     * Gets the value of the posicion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPosicion() {
        return posicion;
    }

    /**
     * Sets the value of the posicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPosicion(Integer value) {
        this.posicion = value;
    }

    /**
     * Gets the value of the recordVuelta property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRecordVuelta() {
        return recordVuelta;
    }

    /**
     * Sets the value of the recordVuelta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRecordVuelta(Double value) {
        this.recordVuelta = value;
    }

}
